### ISSUE TITLE
Footer Social Icons

### ISSUE THREAD

**Issue by joshuag65** [space-pirate-productions/chapmancommunities#28]
Can we add social icons to the footer? What plugin do you suggest?

**Comment by space-pirate-productions** [comment]
@joshuag65 Are you just looking for a row of icons linked to the appropriate social media page (see screenshot for example)?  If so I can create a widget for that pretty quick without the overhead of adding an entire plugin.

**Comment by space-pirate-productions** [comment]
@joshuag65 forgot to attach screenshot, here it is
![image](https://user-images.githubusercontent.com/110199482/191138073-d13ccc01-0f11-479e-b0d7-e7f2a59096c9.png)

**Comment by joshuag65** [comment]
Yes.

Joshua Gale
Senior Director of Marketing
[A picture containing logo  Description automatically generated]<http://chapmancommunities.org/>
8020 Forsyth Boulevard | St. Louis, MO 63105-1707
M: (843) 534-7544
***@***.******@***.***>

[signature_3006834026]<https://www.facebook.com/ChapmanCommunities>

[signature_1978767102]<https://www.linkedin.com/company/chapmancommunities/>


[Graphical user interface  Description automatically generated]<https://www.chapmancommunities.org/>

Take a class<https://connect.chapmancommunities.org/page/events> and sign up for our newsletter<https://www.chapmancommunities.org/newsletter>!


From: Space Pirate Productions ***@***.***>
Date: Monday, September 19, 2022 at 7:41 PM
To: space-pirate-productions/chapmancommunities ***@***.***>
Cc: Gale, Joshua (Chapman Communities) ***@***.***>, Mention ***@***.***>
Subject: Re: [space-pirate-productions/chapmancommunities] Footer Social Icons (Issue #28)

@joshuag65<https://urldefense.com/v3/__https:/github.com/joshuag65__;!!JWpd780U2qK2pF4!Tu9h53R5N4LL1m287iod8BC0UJx5f4TqRBXShNgu9H1MqZDV9FSVrRbaZX7lUSTRvKF79RP-TqpFsfJduYsqJAAkQFiLAVEHqe35$> Are you just looking for a row of icons linked to the appropriate social media page (see screenshot for example)? If so I can create a widget for that pretty quick without the overhead of adding an entire plugin.

**Comment by space-pirate-productions** [comment]
@joshuag65 perfect.  I'll get a widget created and added to the site.  Shouldn't take too long.  Should have it up in a day or so.

**Comment by space-pirate-productions** [comment]
@joshuag65 I've added a "Social Icons" widget (accessible under **Apperance** -> **Widgets**) that you can add to any of the footer columns.  You can select the platform and add whatever URL you want it to link too and it render the icons on the front end.  Let me know if there are any social media platforms that you need that I didn't include.
