### ISSUE TITLE
Social Icons at bottom of home page

### ISSUE THREAD

**Issue by joshuag65** [space-pirate-productions/chapmancommunities#35]
I don't see these yet. I approved your suggestion

**Comment by space-pirate-productions** [comment]
@joshuag65 Sorry, I may not have clarified well enough.  I added the widget to the site as an option but hadn't directly added it to any of the footer widget areas.  I've gone ahead and added it to the "Footer Column One" area and added a couple of icons to it as an example.  You should be able to add more icons from there or move it to another of the widget areas if need be.

![image](https://user-images.githubusercontent.com/110199482/193632429-3d0b45cb-36c2-441e-9e3a-8a9adf9a5b5b.png)

![image](https://user-images.githubusercontent.com/110199482/193632706-33775872-c157-448b-8749-0bbd7641fef8.png)
